export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://localhost:7124/api/';
//export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://sonar-dev.pp.ua/api/';

export const MEDIA_BASE_URL = import.meta.env.VITE_MEDIA_BASE_URL || 'https://localhost:7124/api/';
//export const MEDIA_BASE_URL = import.meta.env.VITE_MEDIA_BASE_URL || 'https://sonar-dev.pp.ua/api/';

export const FRONTEND_BASE_URL = import.meta.env.VITE_FRONTEND_BASE_URL || 'https://sonar-dev.pp.ua/';

export const API_ENDPOINTS = {
    auth: {
        register: 'Auth/register',
        login: 'Auth/login',
        verify2FA: 'Auth/verify-2fa',
        refreshToken: 'Auth/refresh-token',
        changePassword: 'Auth/confirm-password-change',
        requestPasswordChange: 'Auth/request-password-change',
        confirmEmailChange: 'Auth/confirm-email-change',
        confirmEmail: 'Auth/confirm-email',
        getMailChangeToken: 'Auth/request-email-change',
        getSessions: 'Auth/sessions',
        revokeSession: (sessionId: number) => `Auth/sessions/${sessionId}/revoke`,
        revokeAllSessions: 'Auth/sessions/revoke-all',
    },
    user: {
        list: 'User',
        byId: (id: number) => `User/${id}`,
        update: 'User/update',
        updateAvatar: 'User/update-avatar',
        updateVisibility: (collectionId: number) => `User/${collectionId}/visibility`,
        sendFriendRequest: (toUserId: number) => `User/friend-request/${toUserId}`,
        getPendingFriendRequests: 'User/friend-requests/pending',
        getSentFriendRequests: 'User/friend-requests/sent',
        resolveFriendRequest: (requestId: number) => `User/friend-request/${requestId}/resolve`,
        removeFriend: (friendId: number) => `User/friends/${friendId}`,
        getFriends: 'User/friends',
    },
    accessFeature: {
        list: 'AccessFeature',
        byId: (id: number) => `AccessFeature/${id}`,
        byUserId: (userId: number) => `AccessFeature/user/${userId}`,
        assign: (userId: number) => `AccessFeature/assign/${userId}`,
        revoke: (userId: number) => `AccessFeature/revoke/${userId}`,
    },
    subscription: {
        packs: 'Subscription/packs',
        packById: (id: number) => `Subscription/packs/${id}`,
        purchase: 'Subscription/purchase',
        payments: 'Subscription/payments',
        paymentById: (id: number) => `Subscription/payments/${id}`,
        features: 'Subscription/features',
        featureById: (id: number) => `Subscription/features/${id}`,
    },
    report: {
        list: 'Report',
        byId: (id: number) => `Report/${id}`,
        delete: (id: number) => `Report/${id}`,
        create: 'Report',
        close: (id: number) => `Report/${id}/close`,
        filter: 'Report/filter',
        byReporter: (reporterId: number) => `Report/reporter/${reporterId}`,
        open: 'Report/open',
        reasonTypes: 'Report/reason-types',
        reasonTypeById: (id: number) => `Report/reason-types/${id}`,
        entityTypes: 'Report/entity-types',
        entityTypeById: (id: number) => `Report/entity-types/${id}`,
    },
    track: {
        byId: (trackId: number) => `Track/${trackId}`,
        update: (trackId: number) => `Track/${trackId}`,
        delete: (trackId: number) => `Track/${trackId}`,
        updateFile: (trackId: number) => `Track/${trackId}/audio-file`,
        stream: (trackId: number) => `Track/${trackId}/stream`,
        updateVisibility: (trackId: number) => `Track/${trackId}/visibility`,
        toggleFavorite: (trackId: number) => `Track/${trackId}/toggle-favorite`,
    },
    playlist: {
        create: 'Playlist/create',
        delete: (playlistId: number) => `Playlist/${playlistId}`,
        updateName: (playlistId: number) => `Playlist/${playlistId}/update-name`,
        updateCover: (playlistId: number) => `Playlist/${playlistId}/update-cover`,
        addContributor: (playlistId: number, contributorId: number) =>
            `Playlist/${playlistId}/add-contributor/${contributorId}`,
        removeContributor: (playlistId: number, contributorId: number) =>
            `Playlist/${playlistId}/delete-contributor/${contributorId}`,
        addTrack: (playlistId: number, trackId: number) =>
            `Playlist/${playlistId}/add-track/${trackId}`,
        removeTrack: (playlistId: number, trackId: number) =>
            `Playlist/${playlistId}/remove-track/${trackId}`,
        tracks: (playlistId: number) => `Playlist/${playlistId}/tracks`,
        byId: (playlistId: number) => `Playlist/${playlistId}`,
        importCollection: (playlistId: number, collection: string, collectionId: number) =>
            `Playlist/${playlistId}/import-collection/${collection}/${collectionId}`,
        shareLink: (playlistId: number) => `Playlist/${playlistId}/share-link`,
        shareQr: (playlistId: number) => `Playlist/${playlistId}/share-qr`,
        updateVisibility: (playlistId: number) => `Playlist/${playlistId}/visibility`,
    },
    album: {
        byId: (albumId: number) => `Album/${albumId}`,
        upload: 'Album',
        delete: (albumId: number) => `Album/${albumId}`,
        updateName: (albumId: number) => `Album/${albumId}/name`,
        addTrack: (albumId: number) => `Album/${albumId}/add`,
        tracks: (albumId: number) => `Album/${albumId}/tracks`,
        updateCover: (albumId: number) => `Album/${albumId}/cover`,
        shareLink: (albumId: number) => `Album/${albumId}/share-link`,
        shareQr: (albumId: number) => `Album/${albumId}/share-qr`,
        updateVisibility: (albumId: number) => `Album/${albumId}/visibility`,
    },
    distributor: {
        create: 'Distributor',
        list: 'Distributor',
        byId: (id: number) => `Distributor/${id}`,
        update: (id: number) => `Distributor/${id}`,
        delete: (id: number) => `Distributor/${id}`,
        updateKey: (id: number) => `Distributor/update-key/${id}`,
        request: 'Distributor/request',
        requestById: (requestId: number) => `Distributor/request/${requestId}`,
        resolveRequest: (requestId: number) => `Distributor/request/${requestId}`,
    },
    authDistributor: {
        terminateSession: (id: number) => `AuthDistributor/session/${id}`,
        register: 'AuthDistributor/register',
        login: 'AuthDistributor/login',
        refreshToken: 'AuthDistributor/refresh-token',
        revokeSession: (sessionId: number) => `AuthDistributor/${sessionId}/revoke`,
        revokeAllSessions: 'AuthDistributor/sessions/revoke-all',
        getSessions: 'AuthDistributor/sessions',
    },
    distributorMaster: {
        deleteAccount: (id: number) => `DistributorMaster/account/${id}`,
        changeUsername: (id: number) => `DistributorMaster/account/${id}/username`,
        getAccount: (id: number) => `DistributorMaster/account/${id}`,
        changeEmail: (id: number) => `DistributorMaster/account/${id}/email`,
        changePassword: (id: number) => `DistributorMaster/account/${id}/password`,
    },
    chat: {
        list: 'Chat',
        create: 'Chat',
        sendMessage: (chatId: number) => `Chat/${chatId}/send`,
        deleteMessage: (messageId: number) => `Chat/message/${messageId}`,
        editMessage: (messageId: number) => `Chat/message/${messageId}`,
        getMessage: (messageId: number) => `Chat/message/${messageId}`,
        getInfo: (chatId: number) => `Chat/${chatId}/info`,
        getMessages: (chatId: number) => `Chat/${chatId}/messages`,
        addUser: (chatId: number, userId: number) => `Chat/${chatId}/add/${userId}`,
        leave: (chatId: number) => `Chat/${chatId}/leave`,
        removeUser: (chatId: number, userId: number) => `Chat/${chatId}/remove/${userId}`,
        updateCover: (chatId: number) => `Chat/${chatId}/cover`,
        updateName: (chatId: number) => `Chat/${chatId}/name`,
        readMessages: (chatId: number) => `Chat/${chatId}/read`,
        readAllMessages: (chatId: number) => `Chat/${chatId}/read-all`,
    },
    chatSticker: {
        list: 'ChatSticker',
    },
    folder: {
        byId: (folderId: number) => `Folder/${folderId}`,
        list: 'Folder',
        create: 'Folder',
        updateName: (folderId: number) => `Folder/${folderId}/update-name`,
        delete: (folderId: number) => `Folder/${folderId}`,
        addCollection: (folderId: number, collectionId: number) => `Folder/${folderId}/add-collection/${collectionId}`,
        removeCollection: (folderId: number, collectionId: number) => `Folder/${folderId}/remove-collection/${collectionId}`,
        moveCollection: (collectionId: number, targetFolderId: number) => `Folder/move-collection/${collectionId}/to-folder/${targetFolderId}`,
        move: (folderId: number, newParentFolderId: number) => `Folder/${folderId}/move/${newParentFolderId}`,
    },
    userState: {
        updateCurrentPosition: 'UserState/current-position',
        updateListeningTarget: (trackId: number, collectionId?: number) => 
            collectionId ? `UserState/listening/${trackId}/${collectionId}` : `UserState/listening/${trackId}`,
        addToQueue: 'UserState/queue',
        deleteFromQueue: 'UserState/queue',
        updateStatus: (statusId: number) => `UserState/status/${statusId}`,
        updatePrimarySession: 'UserState/session',
    },
    clientSettings: {
        get: 'ClientSettings',
        patch: 'ClientSettings',
        languages: 'ClientSettings/languages',
        themes: 'ClientSettings/themes',
        playbackQualities: 'ClientSettings/playback-qualities',
    },
    gift: {
        send: 'Gift/send',
        accept: (id: number) => `Gift/${id}/accept`,
        received: 'Gift/received',
        sent: 'Gift/sent',
        byId: (id: number) => `Gift/${id}`,
        cancel: (id: number) => `Gift/${id}/cancel`,
        styles: 'Gift/styles',
        styleById: (id: number) => `Gift/styles/${id}`,
    },
    artist: {
        register: 'Artist/register',
        updateName: (artistId: number) => `Artist/${artistId}/update-name`,
        delete: 'Artist',
        createPost: 'Artist',
        deletePost: (postId: number) => `Artist/post/${postId}`,
        updatePost: (postId: number) => `Artist/post/${postId}`,
        updatePostVisibility: (postId: number) => `Artist/${postId}/visibility`,
    },
    blend: {
        updateVisibility: (collectionId: number) => `Blend/${collectionId}/visibility`,
        toggleFavorite: (collectionId: number) => `Blend/${collectionId}/toggle-favorite`,
    },
    share: {
        link: (entityType: string, entityId: number) => `${entityType}/${entityId}/link`,
        qr: (entityType: string, entityId: number) => `${entityType}/${entityId}/qr`,
    },
    collection: {
        updateVisibility: (collectionType: string, collectionId: number) => `${collectionType}/${collectionId}/visibility`,
        toggleFavorite: (collectionType: string, collectionId: number) => `${collectionType}/${collectionId}/toggle-favorite`,
    },
    blob: {
        image: (id: number) => `blob/${id}`,
    },
    search: {
        search: 'Search',
        tracks: 'Search/tracks',
        albums: 'Search/albums',
        playlists: 'Search/playlists',
        artists: 'Search/artists',
        users: 'Search/users',
        suggestions: 'Search/suggestions',
        popular: 'Search/popular',
    },
} as const;
