export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://localhost:7124/api/';

export const API_ENDPOINTS = {
    auth: {
        register: 'Auth/register',
        login: 'Auth/login',
        verify2FA: 'Auth/verify-2fa',
        refreshToken: 'Auth/refresh-token',
        changePassword: 'Auth/confirm-password-change',
        requestPasswordChange: 'Auth/request-password-change',
        confirmEmailChange: 'Auth/confirm-email-change',
        getMailChangeToken: 'Auth/request-email-change',
        getSessions: 'Auth/sessions',
        revokeSession: (sessionId: number) => `Auth/sessions/${sessionId}/revoke`,
        revokeAllSessions: 'Auth/sessions/revoke-all',
    },
    user: {
        list: 'User',
        byId: (id: number) => `User/${id}`,
        update: 'User/update',
        updateAvatar: 'User/update-avatar',
    },
    accessFeature: {
        list: 'AccessFeature',
        byId: (id: number) => `AccessFeature/${id}`,
        byUserId: (userId: number) => `AccessFeature/user/${userId}`,
        assign: (userId: number) => `AccessFeature/assign/${userId}`,
        revoke: (userId: number) => `AccessFeature/revoke/${userId}`,
    },
    subscription: {
        packs: 'Subscription/packs',
        packById: (id: number) => `Subscription/packs/${id}`,
        purchase: 'Subscription/purchase',
        payments: 'Subscription/payments',
        paymentById: (id: number) => `Subscription/payments/${id}`,
        features: 'Subscription/features',
        featureById: (id: number) => `Subscription/features/${id}`,
    },
    report: {
        list: 'Report',
        byId: (id: number) => `Report/${id}`,
        delete: (id: number) => `Report/${id}`,
        create: 'Report',
        close: (id: number) => `Report/${id}/close`,
        filter: 'Report/filter',
        byReporter: (reporterId: number) => `Report/reporter/${reporterId}`,
        open: 'Report/open',
        reasonTypes: 'Report/reason-types',
        reasonTypeById: (id: number) => `Report/reason-types/${id}`,
        entityTypes: 'Report/entity-types',
        entityTypeById: (id: number) => `Report/entity-types/${id}`,
    },
    track: {
        byId: (trackId: number) => `Track/${trackId}`,
        update: (trackId: number) => `Track/${trackId}`,
        delete: (trackId: number) => `Track/${trackId}`,
        updateFile: (trackId: number) => `Track/${trackId}/audio-file`,
        stream: (trackId: number) => `Track/${trackId}/stream`,
        updateVisibility: (trackId: number) => `Track/${trackId}/visibility`,
        toggleFavorite: (trackId: number) => `Track/${trackId}/toggle-favorite`,
    },
    playlist: {
        create: 'Playlist/create',
        delete: (playlistId: number) => `Playlist/${playlistId}`,
        updateName: (playlistId: number) => `Playlist/${playlistId}/update-name`,
        updateCover: (playlistId: number) => `Playlist/${playlistId}/update-cover`,
        addContributor: (playlistId: number, contributorId: number) =>
            `Playlist/${playlistId}/add-contributor/${contributorId}`,
        removeContributor: (playlistId: number, contributorId: number) =>
            `Playlist/${playlistId}/delete-contributor/${contributorId}`,
        addTrack: (playlistId: number, trackId: number) =>
            `Playlist/${playlistId}/add-track/${trackId}`,
        removeTrack: (playlistId: number, trackId: number) =>
            `Playlist/${playlistId}/remove-track/${trackId}`,
        tracks: (playlistId: number) => `Playlist/${playlistId}/tracks`,
        byId: (playlistId: number) => `Playlist/${playlistId}`,
        importCollection: (playlistId: number, collection: string, collectionId: number) =>
            `Playlist/${playlistId}import-collection/${collection}/${collectionId}`,
        shareLink: (playlistId: number) => `Playlist/${playlistId}/share-link`,
        shareQr: (playlistId: number) => `Playlist/${playlistId}/share-qr`,
        updateVisibility: (playlistId: number) => `Playlist/${playlistId}/visibility`,
    },
    album: {
        upload: 'Album',
        delete: (albumId: number) => `Album/${albumId}`,
        updateName: (albumId: number) => `Album/${albumId}/name`,
        addTrack: (albumId: number) => `Album/${albumId}/add`,
        updateCover: (albumId: number) => `Album/${albumId}/cover`,
        shareLink: (albumId: number) => `Album/${albumId}/share-link`,
        shareQr: (albumId: number) => `Album/${albumId}/share-qr`,
        updateVisibility: (albumId: number) => `Album/${albumId}/visibility`,
    },
    distributor: {
        create: 'Distributor',
        list: 'Distributor',
        byId: (id: number) => `Distributor/${id}`,
        update: (id: number) => `Distributor/${id}`,
        delete: (id: number) => `Distributor/${id}`,
        updateKey: (id: number) => `Distributor/update-key/${id}`,
    },
    blob: {
        image: (id: number) => `blob/${id}`,
    },
} as const;
