export const MOCK_LISTEN_NOW_ITEMS = [
    {
        id: 1,
        name: 'Chill Vibes',
        type: 'playlist' as const,
        coverId: 1,
    },
    {
        id: 2,
        name: 'Summer Hits 2024',
        type: 'album' as const,
        coverId: 1,
    },
    {
        id: 3,
        name: 'Workout Mix',
        type: 'playlist' as const,
        coverId: 1,
    },
    {
        id: 4,
        name: 'Indie Essentials',
        type: 'album' as const,
        coverId: 1,
    },
];

export const MOCK_RECENTLY_PLAYED_TRACKS = [
    {
        id: 1,
        title: 'Sunken City Lights',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Moody',
    },
    {
        id: 4,
        title: 'Acoustic Sessions',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Singer Songwriter',
    },
    {
        id: 7,
        title: 'Electric Dreams',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Synthwave',
    },
    {
        id: 8,
        title: 'Ocean Breeze',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Chill Beats',
    },
    {
        id: 9,
        title: 'Night Drive',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Retro Wave',
    },
    {
        id: 10,
        title: 'City Lights',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Urban Vibes',
    },
    {
        id: 11,
        title: 'Sunset Boulevard',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Jazz Collective',
    },
    {
        id: 12,
        title: 'Midnight Run',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Electronic',
    },
    {
        id: 13,
        title: 'Desert Wind',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Ambient',
    },
    {
        id: 14,
        title: 'Neon Nights',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Cyber Punk',
    },
    {
        id: 15,
        title: 'Rainy Day',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Lo-Fi',
    },
    {
        id: 16,
        title: 'Summer Vibes',
        type: 'track' as const,
        coverId: 1,
        artistName: 'Tropical House',
    },
];

export const MOCK_RECENTLY_PLAYED_PLAYLISTS = [
    {
        id: 3,
        title: 'Electronic Pulse',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'DJ Mix',
    },
    {
        id: 6,
        title: 'Jazz Lounge',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Smooth Jazz',
    },
    {
        id: 17,
        title: 'Workout Energy',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Fitness Mix',
    },
    {
        id: 18,
        title: 'Chill Sunday',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Relaxation',
    },
    {
        id: 19,
        title: 'Party Anthems',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Club Hits',
    },
    {
        id: 20,
        title: 'Focus Mode',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Study Music',
    },
    {
        id: 21,
        title: 'Road Trip',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Travel Songs',
    },
    {
        id: 22,
        title: 'Coffee Break',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Acoustic',
    },
    {
        id: 23,
        title: 'Evening Wind Down',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Ambient',
    },
    {
        id: 24,
        title: 'Morning Motivation',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Upbeat',
    },
    {
        id: 25,
        title: 'Indie Discovery',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'New Releases',
    },
    {
        id: 26,
        title: 'Classic Rock',
        type: 'playlist' as const,
        coverId: 1,
        artistName: 'Rock Legends',
    },
];

