name: Deploy Frontend to Test Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version
          docker ps

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL="${{ secrets.VITE_API_BASE_URL }}" \
            -t sonar-frontend:latest .

      - name: Save Docker image to file
        run: |
          docker save sonar-frontend:latest > sonar-frontend.tar

      - name: Copy image to Test Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FRONT_SERVER_HOST }}
          username: ${{ secrets.FRONT_SERVER_USER }}
          key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          source: "sonar-frontend.tar"
          target: "${{ secrets.FRONT_DEPLOY_PATH }}"

      - name: Debug connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONT_SERVER_HOST }}
          username: ${{ secrets.FRONT_SERVER_USER }}
          key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          script: |
            echo
            hostname
            whoami
            ls -la ${{ secrets.FRONT_DEPLOY_PATH }}

      - name: Deploy on Test Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONT_SERVER_HOST }}
          username: ${{ secrets.FRONT_SERVER_USER }}
          key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.FRONT_DEPLOY_PATH }}
            docker stop sonar-frontend || true
            docker rm sonar-frontend || true
            docker rmi sonar-frontend:latest || true
            docker load < sonar-frontend.tar
            docker run -d --name sonar-frontend -p 8082:80 sonar-frontend:latest
